### ISSUE TITLE
Calibrate - command API

### ISSUE THREAD

**Issue by bmahlbrand** [Rokoko/rokoko-studio-unreal-vp-sample-project#7]
https://github.com/Rokoko/Unreal-Demo-Project/blob/0e2900a072b2158b94affb41c2f77ac2bdfb883f/Plugins/Smartsuit/Source/Smartsuit/Private/SmartsuitController.cpp#L119

I noticed all the command API calls are commented out in SmartsuitController, can anyone comment on their stability? i.e. can I uncomment calibrate to use it from my project? Or should I be looking to integrate the CommandAPI code more directly?

**Comment by Chris528** [comment]
We do actually have the command API working, take a look at RokokoStudioCommandAPI.cpp. If you want, you can place a SmartsuitUIController into your map which creates the widget with the command API buttons.

**Comment by bmahlbrand** [comment]
Great, that's what I was thinking should work, just wanted to be sure it wasn't under construction or anything! Thanks for the clarification.
